#' Calculate distance matrix from class assignments
#'
#' Takes the class assignments for each individual generated by the DPM sampler
#' and computes a distance matrix between individuals.
#' 
#' Distance is calculated as the proportion of assignments in which each pair of
#' individuals gets assigned to the same class.  Note that \code{elink()} is the
#' preferred method to do this.
#'
#' @param x a matrix of class assignments, as produced by \code{DPM_sampler()}
#' @param labels a label for each individual
#' 
#' @seealso \link{DPM_sampler}, \link{elink}
#' 
#' @return an object of class \code{dist}
#' @export
as_dist <- function(x, labels) {
	ff <- function(a, b, mat) {
	
		get_dist <- function(x, y) {
			sum(mat[x, ] != mat[y, ]) / ncol(mat)
		}

		mapply(get_dist, a, b)
	}

	out <- outer(1:nrow(x), 1:nrow(x), ff, x)
	dimnames(out) <- list(labels, labels)
	stats::as.dist(out)
}
