# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DPM_sampler <- function(thin, iters, data_, baseline_, labels_, consts_, params) {
    .Call('_unmixR_DPM_sampler', PACKAGE = 'unmixR', thin, iters, data_, baseline_, labels_, consts_, params)
}

elink <- function(ss) {
    .Call('_unmixR_elink', PACKAGE = 'unmixR', ss)
}

rwishart <- function(v, s) {
    .Call('_unmixR_rwishart', PACKAGE = 'unmixR', v, s)
}

rinvwishart <- function(v, s) {
    .Call('_unmixR_rinvwishart', PACKAGE = 'unmixR', v, s)
}

tests2 <- function() {
    .Call('_unmixR_tests2', PACKAGE = 'unmixR')
}

fa <- function() {
    .Call('_unmixR_fa', PACKAGE = 'unmixR')
}

